### ISSUE TITLE
CKAN metapackages for downloaded crafts.

### ISSUE THREAD

**Issue by Ippo343** [Sujimichi/KerbalX#5] opened 2015-02-12 17:04 UTC
(See also KSP-CKAN/CKAN-core#62 )

Making a CKAN metapackage should be straightforward if you have the list of mods used by the craft.
See [here](https://gist.github.com/Ippo343/e96ced511117567c5e1a) for a working example of metapackage.

Anyway, you just need to provide a .ckan file made like this:

	{
		"spec_version": "v1.6",
		"name": "Mod list for TheCraft",
		"identifier": "KerbalX-generated-modpack",
		"kind" : "metapackage",
		"abstract": "Metapackage with all the necessary dependencies for TheCraft",
		"license": "unknown",
		"depends": [
			{
				"name": "Mod1"
			},
			{
				"name": "Mod2"
			}
		],
		"ksp_version": "0.90.0"
	}

The important things for this file are:
* `spec_version` *must* be "v1.6"
* `identifier` must be present, but it can be anything (it's required by the spec, but it's unused for manually installed metapackages)
* `kind` must be `metapackage`
* `ksp_version` *must* be the one you want to install the craft on. I'm afraid right now there's no way in CKAN to support any KSP version.

Also keep in mind that, at this moment, only the command line can install metapackages.

Please feel free to ask any questions you have! :)

**Comment by Ippo343** [comment] 2015-02-12 17:12
Oh, and forgot to add: all the mods you want to list should be in a `depends`, otherwise the user will be given the choice to refuse to install one, which is not what we want here.

**Comment by Sujimichi** [comment] 2015-02-12 20:05
awesome, thanks @Ippo343  You can now get the .ckan file for any craft by adding .ckan to it's url (ie: http://kerbalx.com/hakan/Jolly%20Jeb.ckan)

Got a few questions/notes;
- what happens if the metapackage includes a mod name that ckan does not know?
- pure stock craft still produce a .ckan file, but `depends` is an empty array. Would that cause a problem if a user (totally pointlessly) tried to use a .ckan file for a stock craft?
- how "loose" can mod names be? For example "B9 Aerospace" is known to KX as "B9_Aerospace" because that's how it appears in GameData. Other mods can either be CammelCased or with spaces depending on how their folder in GameData is named. 

My other problem is around mods that have sub mods inside their main folder.  I've not been able to reliably determine sub mods because not all use the same structure. I think this might be less of a problem now as mods have settled on a more reliable structure for sub-mods, so I need to re-visit that in the PartMapper.  But meanwhile that might mean some .ckan files will reference the name of the outer folder-name rather than the actual mod name (ie UmbraSpaceIndustries in the case of Karbonite).

**Comment by Sujimichi** [comment] 2015-02-12 20:08
oh and re the `ksp_version`. For now it just uses the latest KSP version. I could use the ksp version the craft was made in but I don't think that's really that helpful. In the end I can give the user a dropdown option to select which version they want it for but for now its set a 0.90.0

**Comment by Ippo343** [comment] 2015-02-13 11:51
what happens if the metapackage includes a mod name that ckan does not know?

The installation will fail. CKAN will complain that the package with that name is unknown and the installation will be aborted.

    pure stock craft still produce a .ckan file, but depends is an empty array. Would that cause a problem if a user (totally pointlessly) tried to use a .ckan file for a stock craft?

Should be safe, I'll test it later :)

     how "loose" can mod names be?

Unfortunately, not at all. CKAN will only recognize its own identifiers as defined in the metadata files at KSP-CKAN/CKAN-meta, and nothing else :/

**Comment by Dazpoet** [comment] 2015-04-17 08:46
Not sure if this was mentioned somewhere else but seeing as the issue is open I thought I'd just point out that CKAN now supports installation of .ckan files through the GUI as of https://github.com/KSP-CKAN/CKAN-GUI/pull/57

**Comment by Sujimichi** [comment] 2016-02-22 20:28
should have closed this a while back. KerbalX has metapackage support for any object that either has mods or has craft. ie a Craft or ModPack (which has_many mods) can produce a metapackage, and a Hangar or User (which has_many craft) can also produce them.  Any mods not available via CKAN are excluded from the metapackage.

**Closed by Sujimichi** 2016-02-22 20:28 UTC
